export const YOUTUBE_API_KEY = 'AIzaSyDjSQp1NtdHgtAZT2_3gQADTnmpeppYdk8';
export const ANARTZ_MUGIKA_CHANNEL_ID = 'UCTh7-deUJBNv2tHRiMGcXxg';
export const ANARTZ_MUGIKA_CHANNEL_UPLOADS = 'UUTh7-deUJBNv2tHRiMGcXxg';
